### ISSUE TITLE
Name & Exec path are not working for Linux

### ISSUE THREAD

**Issue by ethielknd** [Izurii/easy-auto-launch#6]
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Linux
- Node version (run `node -v`): v16.15.0
- auto-launch version: ^6.0.2
- The options you're passing to auto-launch: name and path
- Are you using NW.js or Electron? Electron
  - If so, which version? 18.3.2
  - If you're using Electron, are you using auto-launch from the main process or a renderer process? Main process
- Can you reproduce this with a simple Hello World example app? Not sure, probably
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem? I can't

---

Hello,
I have an Electron app build for Linux, the options that I pass to auto-launch when instancing the object are:
```
new AutoLaunch({
    name: 'My name app',
    path: !process.env.APPIMAGE ? app.getAppPath() : process.env.APPIMAGE,
})
```
`app.getAppPath()` is for `.deb`
When I check the desktop entry, the `Exec` points to `/opt/My name app/resourses/app.asar` and when I shutdown and start again the laptop, the app doesn't launch. I would like to know if the path is correct or I'm missing something else

Also, the `name` is not working, the desktop entry file takes `app.asar` as name instead of the one that I pass as param

**Comment by ethielc** [comment]
Ok so I fixed this by changing the `app.getAppPath()` to `app.getPath('exe')`, the name was actually working after that change

**Comment by ethielknd** [comment]
Ok so I fixed this by changing the app.getAppPath() to app.getPath('exe'), the name was actually working after that change
